// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAOykCjhO5LPsMGHN23BgXmEtVc_N9508',
    appId: '1:478454717192:web:4b12177f4b804433faeabd',
    messagingSenderId: '478454717192',
    projectId: 'fir-notifications-608fd',
    authDomain: 'fir-notifications-608fd.firebaseapp.com',
    storageBucket: 'fir-notifications-608fd.appspot.com',
    measurementId: 'G-CTQ8V5H4C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrFwXaSTR5MsKEySb7WTpi_rDR5ZO01fc',
    appId: '1:478454717192:android:608dd4f9c2f72810faeabd',
    messagingSenderId: '478454717192',
    projectId: 'fir-notifications-608fd',
    storageBucket: 'fir-notifications-608fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA92eXUSAv7MzP2OOBpCBBl3J0Jpdjeung',
    appId: '1:478454717192:ios:d313f52de3d78759faeabd',
    messagingSenderId: '478454717192',
    projectId: 'fir-notifications-608fd',
    storageBucket: 'fir-notifications-608fd.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA92eXUSAv7MzP2OOBpCBBl3J0Jpdjeung',
    appId: '1:478454717192:ios:d313f52de3d78759faeabd',
    messagingSenderId: '478454717192',
    projectId: 'fir-notifications-608fd',
    storageBucket: 'fir-notifications-608fd.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAOykCjhO5LPsMGHN23BgXmEtVc_N9508',
    appId: '1:478454717192:web:12d57188e1311569faeabd',
    messagingSenderId: '478454717192',
    projectId: 'fir-notifications-608fd',
    authDomain: 'fir-notifications-608fd.firebaseapp.com',
    storageBucket: 'fir-notifications-608fd.appspot.com',
    measurementId: 'G-FE8S3YYQ4X',
  );
}
